services:
  pullup-counter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-pullup-counter
    volumes:
      - .:/app
      - ./input_videos:/app/input_videos
      - ./output_videos:/app/output_videos
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    env_file:
      - .env
    networks:
      - pullup-network
    stdin_open: true
    tty: true
    working_dir: /app
    command: tail -f /dev/null  # Keep container running
    depends_on:
      - setup-dirs

  setup-dirs:
    image: busybox:latest
    container_name: setup-directories
    volumes:
      - .:/app
    command: >
      sh -c "
        mkdir -p /app/input_videos &&
        mkdir -p /app/output_videos &&
        echo 'Directories created successfully'
      "

networks:
  pullup-network:
    driver: bridge

volumes:
  input_videos:
  output_videos: 